os: linux
language: cpp
matrix:
  include:
    - env: TEST=shellcheck
      services:
        - docker
      script: |
        set -e
        shopt -s globstar nullglob
        CHECK=( ec2-automate-backup/ec2-automate-backup.sh )
        [[ ${#CHECK[@]} -eq 0 ]] && exit
        docker run -v $(pwd):$(pwd) -w $(pwd) \
          koalaman/shellcheck-alpine:v0.4.6 -x "${CHECK[@]}"
branches:
  only:
  - master
notifications:
  email: false
